/**
 * Generated by scripts/import-csv.js from pmdg-737-maor-v2.csv — do not edit by hand.
 * Regenerate: node scripts/import-csv.js data/pmdg-737-maor-v2.csv pmdg737 js/profile-pmdg737.js
 */

const PROFILE_PMDG737 = {
  "id": "pmdg737",
  "name": "Boeing 737 PROC +CHECKLIST+GSX",
  "phases": [
    {
      "id": "pmdg737.0",
      "name": "PREFLIGHT",
      "items": [
        {
          "id": "pmdg737.0.0",
          "challenge": "GPU & JETWAY OR STAIRS",
          "response": "REQUEST",
          "note": "GSX"
        },
        {
          "id": "pmdg737.0.1",
          "challenge": "FUEL & CATERING",
          "response": "REQUEST",
          "note": "GSX"
        },
        {
          "id": "pmdg737.0.2",
          "challenge": "PARKING BRAKE",
          "response": "SET"
        },
        {
          "id": "pmdg737.0.3",
          "challenge": "BATTERY",
          "response": "GUARD CLOSED"
        },
        {
          "id": "pmdg737.0.4",
          "challenge": "STANDBY POWER",
          "response": "GUARD CLOSED"
        },
        {
          "id": "pmdg737.0.5",
          "challenge": "L CENTER FUEL PUMP",
          "response": "AS REQ"
        },
        {
          "id": "pmdg737.0.6",
          "challenge": "L AFT FUEL PUMP",
          "response": "AS REQ"
        },
        {
          "id": "pmdg737.0.7",
          "challenge": "APU",
          "response": "START"
        },
        {
          "id": "pmdg737.0.8",
          "challenge": "APU GEN",
          "response": "ON"
        },
        {
          "id": "pmdg737.0.9",
          "challenge": "POS LIGHTS",
          "response": "STEADY"
        },
        {
          "id": "pmdg737.0.10",
          "challenge": "LOGO LIGHT",
          "response": "AS REQ"
        },
        {
          "id": "pmdg737.0.11",
          "challenge": "CABIN LIGHTS",
          "response": "AS REQ"
        },
        {
          "id": "pmdg737.0.12",
          "challenge": "EMER EXIT LIGHTS",
          "response": "GUARD CLOSED"
        },
        {
          "id": "pmdg737.0.13",
          "challenge": "PASSENGER SIGNS",
          "response": "ON"
        },
        {
          "id": "pmdg737.0.14",
          "challenge": "PACKS",
          "response": "AUTO / HIGH"
        },
        {
          "id": "pmdg737.0.15",
          "challenge": "IRS MODE SELECTORS",
          "response": "OFF > NAV"
        },
        {
          "id": "pmdg737.0.16",
          "challenge": "FMC",
          "response": "SET"
        },
        {
          "id": "pmdg737.0.17",
          "challenge": "Flight-plan Clearance",
          "response": "Request"
        },
        {
          "id": "pmdg737.0.18",
          "challenge": "TRANSPONDER",
          "response": "SET"
        },
        {
          "id": "pmdg737.0.19",
          "challenge": "IAS / MACH SPEED",
          "response": "SET"
        },
        {
          "id": "pmdg737.0.20",
          "challenge": "HDG / TAKEOFF RWY",
          "response": "SET"
        },
        {
          "id": "pmdg737.0.21",
          "challenge": "INITIAL ALT",
          "response": "SET"
        },
        {
          "id": "pmdg737.0.22",
          "challenge": "YAW DAMPER",
          "response": "ON"
        },
        {
          "id": "pmdg737.0.23",
          "challenge": "WINDOW HEAT",
          "response": "ON"
        },
        {
          "id": "pmdg737.0.24",
          "challenge": "FLIGHT ALTITUDE",
          "response": "SET"
        },
        {
          "id": "pmdg737.0.25",
          "challenge": "LANDING ALTITUDE",
          "response": "SET"
        },
        {
          "id": "pmdg737.0.26",
          "challenge": "FLIGHT DIRECTORS",
          "response": "ON"
        },
        {
          "id": "pmdg737.0.27",
          "challenge": "LNAV",
          "response": "AS REQ"
        },
        {
          "id": "pmdg737.0.28",
          "challenge": "VNAV",
          "response": "AS REQ"
        },
        {
          "id": "pmdg737.0.29",
          "challenge": "MINIMUMS REF",
          "response": "BARO or RADIO"
        },
        {
          "id": "pmdg737.0.30",
          "challenge": "MINIMUMS",
          "response": "SET"
        },
        {
          "id": "pmdg737.0.31",
          "challenge": "ALTIMETER REF",
          "response": "IN or HPA"
        },
        {
          "id": "pmdg737.0.32",
          "challenge": "AUTO BRAKE",
          "response": "RTO"
        },
        {
          "id": "pmdg737.0.33",
          "challenge": "COM RADIOS",
          "response": "SET"
        },
        {
          "id": "pmdg737.0.34",
          "challenge": "PASSENGER BOARDING",
          "response": "REQUEST",
          "note": "GSX"
        }
      ]
    },
    {
      "id": "pmdg737.1",
      "name": "PREFLIGHT CHECKLIST",
      "items": [
        {
          "id": "pmdg737.1.0",
          "challenge": "OXYGEN",
          "response": "TESTED 100%"
        },
        {
          "id": "pmdg737.1.1",
          "challenge": "NAV TRANSER & DISPLAY SWITCHS",
          "response": "NORMAL, AUTO"
        },
        {
          "id": "pmdg737.1.2",
          "challenge": "WINDOWHEAT",
          "response": "ON"
        },
        {
          "id": "pmdg737.1.3",
          "challenge": "PERSSURIZATION MODE SELECTOR",
          "response": "AUTO"
        },
        {
          "id": "pmdg737.1.4",
          "challenge": "FLIGHT INSTRUMENTS",
          "response": "HEADIND____, ALTIMETER_____"
        },
        {
          "id": "pmdg737.1.5",
          "challenge": "PARKING BRAKE",
          "response": "SET"
        },
        {
          "id": "pmdg737.1.6",
          "challenge": "ENGINE START LEVERS",
          "response": "CUTOFF"
        }
      ]
    },
    {
      "id": "pmdg737.2",
      "name": "BEFORE START",
      "items": [
        {
          "id": "pmdg737.2.0",
          "challenge": "Pushback & Startup Clearance",
          "response": "Request"
        },
        {
          "id": "pmdg737.2.1",
          "challenge": "AUTOTHROTTLE",
          "response": "ARM"
        },
        {
          "id": "pmdg737.2.2",
          "challenge": "L & R C FUEL PUMPS",
          "response": "AS REQ"
        },
        {
          "id": "pmdg737.2.3",
          "challenge": "A & F FUEL PUMPS",
          "response": "ON"
        },
        {
          "id": "pmdg737.2.4",
          "challenge": "ELEC HYD PUMPS",
          "response": "ON"
        },
        {
          "id": "pmdg737.2.5",
          "challenge": "ANTI COLL LIGHT",
          "response": "ON"
        },
        {
          "id": "pmdg737.2.6",
          "challenge": "PARKING BRAKE",
          "response": "SET"
        },
        {
          "id": "pmdg737.2.7",
          "challenge": "GROUND EQUIPMENT",
          "response": "REMOVED"
        },
        {
          "id": "pmdg737.2.8",
          "challenge": "ENGINE AREA",
          "response": "CLEAR"
        }
      ]
    },
    {
      "id": "pmdg737.3",
      "name": "BEFORE START CHECKLIST",
      "items": [
        {
          "id": "pmdg737.3.0",
          "challenge": "FLIGHT DECK DOOR",
          "response": "CLOSE & LOCK"
        },
        {
          "id": "pmdg737.3.1",
          "challenge": "FUEL",
          "response": "___KG , PUMP ON"
        },
        {
          "id": "pmdg737.3.2",
          "challenge": "SINGS",
          "response": "ON"
        },
        {
          "id": "pmdg737.3.3",
          "challenge": "MCP",
          "response": "V2__ , HDG__ , ALT__"
        },
        {
          "id": "pmdg737.3.4",
          "challenge": "TAKEOFF SPEED",
          "response": "V1__ , VR__ , V2__"
        },
        {
          "id": "pmdg737.3.5",
          "challenge": "CDU PREFLIGHT",
          "response": "COMPLETED"
        },
        {
          "id": "pmdg737.3.6",
          "challenge": "RUDDER & AIRERON TRIM",
          "response": "FREE & 0"
        },
        {
          "id": "pmdg737.3.7",
          "challenge": "TAXI & TAKEOFF BRIEFING",
          "response": "COMPLETED"
        },
        {
          "id": "pmdg737.3.8",
          "challenge": "ANTI COLL LIGHT",
          "response": "ON"
        }
      ]
    },
    {
      "id": "pmdg737.4",
      "name": "ENGINE START",
      "items": [
        {
          "id": "pmdg737.4.0",
          "challenge": "SEC DISPLAY UNIT",
          "response": "ENGINE"
        },
        {
          "id": "pmdg737.4.1",
          "challenge": "PACKS",
          "response": "OFF"
        },
        {
          "id": "pmdg737.4.2",
          "challenge": "ENGINE 1 START SWITCH",
          "response": "GND"
        },
        {
          "id": "pmdg737.4.3",
          "challenge": "ENGINE 1 FUEL CONTROL LEVER",
          "response": "RUN"
        },
        {
          "id": "pmdg737.4.4",
          "challenge": "ENGINE 2 START SWITCH",
          "response": "GND"
        },
        {
          "id": "pmdg737.4.5",
          "challenge": "ENGINE 2 FUEL CONTROL LEVER",
          "response": "RUN"
        }
      ]
    },
    {
      "id": "pmdg737.5",
      "name": "BEFORE TAXI",
      "items": [
        {
          "id": "pmdg737.5.0",
          "challenge": "GENERATORS 1 & 2",
          "response": "ON"
        },
        {
          "id": "pmdg737.5.1",
          "challenge": "PROBE HEAT",
          "response": "ON"
        },
        {
          "id": "pmdg737.5.2",
          "challenge": "WING ANTI ICE",
          "response": "AS REQ"
        },
        {
          "id": "pmdg737.5.3",
          "challenge": "ENGINE ANTI ICE",
          "response": "AS REQ"
        },
        {
          "id": "pmdg737.5.4",
          "challenge": "PACKS",
          "response": "AUTO"
        },
        {
          "id": "pmdg737.5.5",
          "challenge": "ISOLATION VALVE",
          "response": "AUTO"
        },
        {
          "id": "pmdg737.5.6",
          "challenge": "APU BLEED",
          "response": "OFF"
        },
        {
          "id": "pmdg737.5.7",
          "challenge": "APU",
          "response": "OFF"
        },
        {
          "id": "pmdg737.5.8",
          "challenge": "ENG START SWITCHES",
          "response": "CONT"
        },
        {
          "id": "pmdg737.5.9",
          "challenge": "FLAPS",
          "response": "AS REQ"
        },
        {
          "id": "pmdg737.5.10",
          "challenge": "ELEVATOR TRIM",
          "response": "SET FOR TAKE-OFF"
        },
        {
          "id": "pmdg737.5.11",
          "challenge": "FLIGHT CONTROLS",
          "response": "FREE AND CORRECT"
        },
        {
          "id": "pmdg737.5.12",
          "challenge": "RECALL (737-800 only)",
          "response": "CHECK"
        },
        {
          "id": "pmdg737.5.13",
          "challenge": "LOWER DISPLAY UNIT (DU)",
          "response": "OFF"
        },
        {
          "id": "pmdg737.5.14",
          "challenge": "Taxi Clearance",
          "response": "Request"
        },
        {
          "id": "pmdg737.5.15",
          "challenge": "TAXI LIGHTS",
          "response": "ON"
        },
        {
          "id": "pmdg737.5.16",
          "challenge": "RWY TURN-OFF LIGHTS",
          "response": "AS REQ"
        }
      ]
    },
    {
      "id": "pmdg737.6",
      "name": "BEFORE TAXI CHECKLIST",
      "items": [
        {
          "id": "pmdg737.6.0",
          "challenge": "GENERATORS",
          "response": "ON"
        },
        {
          "id": "pmdg737.6.1",
          "challenge": "PROBE HEAT",
          "response": "ON"
        },
        {
          "id": "pmdg737.6.2",
          "challenge": "ANTI ICE",
          "response": "___"
        },
        {
          "id": "pmdg737.6.3",
          "challenge": "ISOLATION VALVE",
          "response": "AUTO"
        },
        {
          "id": "pmdg737.6.4",
          "challenge": "ENG START SWITCHES",
          "response": "CONT"
        },
        {
          "id": "pmdg737.6.5",
          "challenge": "RECALL",
          "response": "CHECKED"
        },
        {
          "id": "pmdg737.6.6",
          "challenge": "AUTO BRAKE",
          "response": "RTO"
        },
        {
          "id": "pmdg737.6.7",
          "challenge": "ENG START LEVERS",
          "response": "IDLE DETENT"
        },
        {
          "id": "pmdg737.6.8",
          "challenge": "FLIGHT CONTROLS",
          "response": "CHECKED"
        },
        {
          "id": "pmdg737.6.9",
          "challenge": "GROUND EQUIPMENT",
          "response": "CLEAR"
        }
      ]
    },
    {
      "id": "pmdg737.7",
      "name": "TAXI",
      "items": [
        {
          "id": "pmdg737.7.0",
          "challenge": "BRKS/GYRO/TURN COORDINATOR",
          "response": "CHECK",
          "note": "CHECK during taxi"
        }
      ]
    },
    {
      "id": "pmdg737.8",
      "name": "BEFORE TAKEOFF",
      "items": [
        {
          "id": "pmdg737.8.0",
          "challenge": "PARKING BRAKE",
          "response": "SET"
        },
        {
          "id": "pmdg737.8.1",
          "challenge": "FUEL FLOW",
          "response": "RESET, then RATE"
        },
        {
          "id": "pmdg737.8.2",
          "challenge": "C FUEL PUMPS",
          "response": "AS REQ"
        },
        {
          "id": "pmdg737.8.3",
          "challenge": "DE-ICE",
          "response": "AS REQ"
        },
        {
          "id": "pmdg737.8.4",
          "challenge": "CABIN LIGHTS",
          "response": "AS REQ"
        },
        {
          "id": "pmdg737.8.5",
          "challenge": "FLIGHT INSTRUMENTS",
          "response": "CHECK"
        },
        {
          "id": "pmdg737.8.6",
          "challenge": "ENGINE INSTRUMENTS",
          "response": "CHECK"
        },
        {
          "id": "pmdg737.8.7",
          "challenge": "TAKE-OFF DATA",
          "response": "(V1, VR, V2) CHECK"
        },
        {
          "id": "pmdg737.8.8",
          "challenge": "NAV EQUIPMENT",
          "response": "CHECK"
        }
      ]
    },
    {
      "id": "pmdg737.9",
      "name": "BEFORE TAKE OFF CHECKLIST",
      "items": [
        {
          "id": "pmdg737.9.0",
          "challenge": "FLAPS",
          "response": "__ GREEN LIGHT"
        },
        {
          "id": "pmdg737.9.1",
          "challenge": "STABILIZER TRIM",
          "response": "__ UNITS"
        }
      ]
    },
    {
      "id": "pmdg737.10",
      "name": "BEFORE TAKEOFF (continued)",
      "items": [
        {
          "id": "pmdg737.10.0",
          "challenge": "Takeoff Clearance",
          "response": "Request"
        },
        {
          "id": "pmdg737.10.1",
          "challenge": "LANDING LIGHTS",
          "response": "ON"
        },
        {
          "id": "pmdg737.10.2",
          "challenge": "STROBE LIGHT",
          "response": "ON"
        },
        {
          "id": "pmdg737.10.3",
          "challenge": "TAXI LIGHTS",
          "response": "OFF"
        },
        {
          "id": "pmdg737.10.4",
          "challenge": "TRANSPONDER",
          "response": "TA/RA"
        },
        {
          "id": "pmdg737.10.5",
          "challenge": "TFC",
          "response": "PUSH ON"
        },
        {
          "id": "pmdg737.10.6",
          "challenge": "CLOCK",
          "response": "START"
        }
      ]
    },
    {
      "id": "pmdg737.11",
      "name": "AFTER TAKEOFF",
      "items": [
        {
          "id": "pmdg737.11.0",
          "challenge": "POSITIVE RATE OF CLIMB",
          "response": "GEAR UP"
        },
        {
          "id": "pmdg737.11.1",
          "challenge": "AUTO-BRAKE",
          "response": "OFF"
        },
        {
          "id": "pmdg737.11.2",
          "challenge": "ENGINE START SWITCHES",
          "response": "OFF"
        },
        {
          "id": "pmdg737.11.3",
          "challenge": "GEAR LEVER",
          "response": "OFF POSITION"
        },
        {
          "id": "pmdg737.11.4",
          "challenge": "RWY TURN-OFF LIGHTS",
          "response": "OFF"
        },
        {
          "id": "pmdg737.11.5",
          "challenge": "CABIN LIGHTS",
          "response": "AS REQ"
        }
      ]
    },
    {
      "id": "pmdg737.12",
      "name": "CLIMB-OUT",
      "items": [
        {
          "id": "pmdg737.12.0",
          "challenge": "CMD A or B",
          "response": "ENGAGE",
          "note": "(when suitable)"
        }
      ]
    },
    {
      "id": "pmdg737.13",
      "name": "CLIMB-OUT — Passing TA",
      "items": [
        {
          "id": "pmdg737.13.0",
          "challenge": "ALTIMETER",
          "response": "SET STD",
          "note": "(29.92 / 1013)"
        }
      ]
    },
    {
      "id": "pmdg737.14",
      "name": "CLIMB-OUT — BELOW 10'000FT",
      "items": [
        {
          "id": "pmdg737.14.0",
          "challenge": "MAX SPEED",
          "response": "250 KIAS"
        },
        {
          "id": "pmdg737.14.1",
          "challenge": "ATC",
          "response": "AS REQ"
        }
      ]
    },
    {
      "id": "pmdg737.15",
      "name": "CLIMB-OUT — AFTER TAKEOFF CHECKLIST",
      "items": [
        {
          "id": "pmdg737.15.0",
          "challenge": "ENGINE BLEEDS",
          "response": "ON"
        },
        {
          "id": "pmdg737.15.1",
          "challenge": "PACKS",
          "response": "AUTO"
        },
        {
          "id": "pmdg737.15.2",
          "challenge": "LANDING GEAR",
          "response": "UP & OFF"
        },
        {
          "id": "pmdg737.15.3",
          "challenge": "FLAPS",
          "response": "UP, NO LIGHTS"
        }
      ]
    },
    {
      "id": "pmdg737.16",
      "name": "CLIMB-OUT — Passing 10'000 ft",
      "items": [
        {
          "id": "pmdg737.16.0",
          "challenge": "LANDING LIGHTS",
          "response": "OFF"
        },
        {
          "id": "pmdg737.16.1",
          "challenge": "FASTEN SEAT BELTS",
          "response": "OFF"
        },
        {
          "id": "pmdg737.16.2",
          "challenge": "C FUEL PUMPS",
          "response": "AS REQ"
        }
      ]
    },
    {
      "id": "pmdg737.17",
      "name": "CRUISE & DESCENT PREPERATION",
      "items": [
        {
          "id": "pmdg737.17.0",
          "challenge": "ENGINE & INSTRUMENTS",
          "response": "MONITOR"
        },
        {
          "id": "pmdg737.17.1",
          "challenge": "FUEL QUANTITY",
          "response": "CHECK"
        },
        {
          "id": "pmdg737.17.2",
          "challenge": "LIGHTS",
          "response": "AS REQ"
        }
      ]
    },
    {
      "id": "pmdg737.18",
      "name": "CRUISE & DESCENT PREPERATION — Before TOD (100MN)",
      "items": [
        {
          "id": "pmdg737.18.0",
          "challenge": "ATIS / AIRPORT INFORMATION",
          "response": "CHECK"
        },
        {
          "id": "pmdg737.18.1",
          "challenge": "ALTIMETER",
          "response": "CHECK"
        },
        {
          "id": "pmdg737.18.2",
          "challenge": "RADIOS",
          "response": "SET"
        },
        {
          "id": "pmdg737.18.3",
          "challenge": "RESET MCP ALTITUDE",
          "response": "CHECK"
        },
        {
          "id": "pmdg737.18.4",
          "challenge": "FMC APPR SPEED REF",
          "response": "SET"
        },
        {
          "id": "pmdg737.18.5",
          "challenge": "LOCALIZER FREQ",
          "response": "SET"
        },
        {
          "id": "pmdg737.18.6",
          "challenge": "ILS LOC COURSE",
          "response": "SET"
        }
      ]
    },
    {
      "id": "pmdg737.19",
      "name": "Descent",
      "items": [
        {
          "id": "pmdg737.19.0",
          "challenge": "DE-ICE",
          "response": "AS REQ"
        },
        {
          "id": "pmdg737.19.1",
          "challenge": "LANDING ALT",
          "response": "CHECK"
        },
        {
          "id": "pmdg737.19.2",
          "challenge": "RECALL (737-800 only)",
          "response": "CHECK"
        },
        {
          "id": "pmdg737.19.3",
          "challenge": "RADIO ALT / BARO MIN",
          "response": "SET, CHECK"
        },
        {
          "id": "pmdg737.19.4",
          "challenge": "AUTO BRAKE",
          "response": "AS REQ"
        }
      ]
    },
    {
      "id": "pmdg737.20",
      "name": "DESCENT CHECKLIST",
      "items": [
        {
          "id": "pmdg737.20.0",
          "challenge": "PERSSURIZATION",
          "response": "LAND ALT__ CHECKED"
        },
        {
          "id": "pmdg737.20.1",
          "challenge": "RECALL",
          "response": "CHECKED"
        },
        {
          "id": "pmdg737.20.2",
          "challenge": "AUTO BRAKE",
          "response": "__ SET"
        },
        {
          "id": "pmdg737.20.3",
          "challenge": "LANDING DATA",
          "response": "VREF__ , MINIMUMS__"
        },
        {
          "id": "pmdg737.20.4",
          "challenge": "APPROACH BRIEFING",
          "response": "COMPLETED"
        }
      ]
    },
    {
      "id": "pmdg737.21",
      "name": "CRUISE & DESCENT PREPERATION — Passing TA",
      "items": [
        {
          "id": "pmdg737.21.0",
          "challenge": "ALTIMETER",
          "response": "RESET TO LOCAL"
        }
      ]
    },
    {
      "id": "pmdg737.22",
      "name": "CRUISE & DESCENT PREPERATION — Below 10'000 ft",
      "items": [
        {
          "id": "pmdg737.22.0",
          "challenge": "SPEED",
          "response": "250 KIAS"
        },
        {
          "id": "pmdg737.22.1",
          "challenge": "LANDING LIGHTS",
          "response": "ON"
        },
        {
          "id": "pmdg737.22.2",
          "challenge": "PASSENGER SIGNS",
          "response": "ON"
        },
        {
          "id": "pmdg737.22.3",
          "challenge": "Weather",
          "response": "CHECK",
          "note": "ATIS, Flight Services"
        }
      ]
    },
    {
      "id": "pmdg737.23",
      "name": "APPROACH",
      "items": [
        {
          "id": "pmdg737.23.0",
          "challenge": "ALTIMETER",
          "response": "CHECK"
        },
        {
          "id": "pmdg737.23.1",
          "challenge": "LOCALIZER FREQ",
          "response": "CHECK"
        },
        {
          "id": "pmdg737.23.2",
          "challenge": "LOCALIZER COURSE",
          "response": "CHECK"
        },
        {
          "id": "pmdg737.23.3",
          "challenge": "APP",
          "response": "ARM"
        },
        {
          "id": "pmdg737.23.4",
          "challenge": "GLIDESLOPE ALIVE",
          "response": "GEAR DOWN"
        },
        {
          "id": "pmdg737.23.5",
          "challenge": "FLAPS",
          "response": "15 OR 30 OR 40"
        },
        {
          "id": "pmdg737.23.6",
          "challenge": "SPEED BRAKE",
          "response": "ARM"
        },
        {
          "id": "pmdg737.23.7",
          "challenge": "2ND AUTOPILOT",
          "response": "ARM",
          "note": "(when ILS established)"
        },
        {
          "id": "pmdg737.23.8",
          "challenge": "ENGINE START SWITCHES",
          "response": "CONT"
        },
        {
          "id": "pmdg737.23.9",
          "challenge": "LANDING FLAPS",
          "response": "SET"
        }
      ]
    },
    {
      "id": "pmdg737.24",
      "name": "APPROACH CHECKLIST",
      "items": [
        {
          "id": "pmdg737.24.0",
          "challenge": "ALTIMETER",
          "response": "__ SET"
        },
        {
          "id": "pmdg737.24.1",
          "challenge": "SEATBELTS",
          "response": "ON"
        }
      ]
    },
    {
      "id": "pmdg737.25",
      "name": "LANDING",
      "items": [
        {
          "id": "pmdg737.25.0",
          "challenge": "GO-AROUND ALTITUDE",
          "response": "SET"
        },
        {
          "id": "pmdg737.25.1",
          "challenge": "RWY TURN-OFF LIGHTS",
          "response": "ON"
        },
        {
          "id": "pmdg737.25.2",
          "challenge": "LANDING GEAR",
          "response": "CHECK DOWN"
        },
        {
          "id": "pmdg737.25.3",
          "challenge": "AUTOPILOT",
          "response": "AS REQ"
        },
        {
          "id": "pmdg737.25.4",
          "challenge": "AUTO-THRUST",
          "response": "AS REQ"
        }
      ]
    },
    {
      "id": "pmdg737.26",
      "name": "LANDING CHECKLIST",
      "items": [
        {
          "id": "pmdg737.26.0",
          "challenge": "ENG START SWITCHES",
          "response": "CONT"
        },
        {
          "id": "pmdg737.26.1",
          "challenge": "SPEED BRAKE",
          "response": "AERMD"
        },
        {
          "id": "pmdg737.26.2",
          "challenge": "LANDING GEAR",
          "response": "DOWN"
        },
        {
          "id": "pmdg737.26.3",
          "challenge": "FLAPS",
          "response": "__ GREEN LIGHT"
        }
      ]
    },
    {
      "id": "pmdg737.27",
      "name": "LANDING — After Touch-Down",
      "items": [
        {
          "id": "pmdg737.27.0",
          "challenge": "THRUST REVERSE",
          "response": "ENGAGE"
        },
        {
          "id": "pmdg737.27.1",
          "challenge": "AUTOPILOT",
          "response": "OFF"
        },
        {
          "id": "pmdg737.27.2",
          "challenge": "AUTOTHRUST",
          "response": "OFF"
        },
        {
          "id": "pmdg737.27.3",
          "challenge": "AT 60 KTS",
          "response": "REV THRUST TO IDLE"
        },
        {
          "id": "pmdg737.27.4",
          "challenge": "AT 30 KTS",
          "response": "AUTO-BRAKE DISENGAGE"
        }
      ]
    },
    {
      "id": "pmdg737.28",
      "name": "AFTER LANDING",
      "items": [
        {
          "id": "pmdg737.28.0",
          "challenge": "TRANSPONDER",
          "response": "OFF"
        },
        {
          "id": "pmdg737.28.1",
          "challenge": "FLAPS",
          "response": "RETRACT"
        },
        {
          "id": "pmdg737.28.2",
          "challenge": "SPEED BRAKE",
          "response": "DOWN"
        },
        {
          "id": "pmdg737.28.3",
          "challenge": "LANDING LIGHTS",
          "response": "OFF"
        },
        {
          "id": "pmdg737.28.4",
          "challenge": "STROBE LIGHTS",
          "response": "OFF"
        },
        {
          "id": "pmdg737.28.5",
          "challenge": "TAXI LIGHTS",
          "response": "ON"
        },
        {
          "id": "pmdg737.28.6",
          "challenge": "CABIN LIGHTS",
          "response": "AS REQ"
        },
        {
          "id": "pmdg737.28.7",
          "challenge": "ANTI ICE",
          "response": "AS REQ"
        },
        {
          "id": "pmdg737.28.8",
          "challenge": "APU",
          "response": "START / CHECK RUN"
        },
        {
          "id": "pmdg737.28.9",
          "challenge": "PROBE HEAT",
          "response": "OFF"
        },
        {
          "id": "pmdg737.28.10",
          "challenge": "ENG START SWITCHES",
          "response": "OFF"
        },
        {
          "id": "pmdg737.28.11",
          "challenge": "AUTO-BRAKE",
          "response": "OFF"
        },
        {
          "id": "pmdg737.28.12",
          "challenge": "Taxi to Assigned Gate/Parking (Speed Max 20 knots)",
          "response": ""
        },
        {
          "id": "pmdg737.28.13",
          "challenge": "RWY TURNOFF LIGHTS",
          "response": "OFF"
        },
        {
          "id": "pmdg737.28.14",
          "challenge": "APU GEN",
          "response": "ON / CHECK VOLTS"
        },
        {
          "id": "pmdg737.28.15",
          "challenge": "Turning Into The Gate:",
          "response": ""
        },
        {
          "id": "pmdg737.28.16",
          "challenge": "TAXI LIGHTS",
          "response": "OFF"
        }
      ]
    },
    {
      "id": "pmdg737.29",
      "name": "PARKING",
      "items": [
        {
          "id": "pmdg737.29.0",
          "challenge": "PARKING BRAKES",
          "response": "SET"
        },
        {
          "id": "pmdg737.29.1",
          "challenge": "ENGINE FUEL CONTROL LEVERS",
          "response": "OFF"
        },
        {
          "id": "pmdg737.29.2",
          "challenge": "GROUND CONTACT",
          "response": "ESTABLISH"
        },
        {
          "id": "pmdg737.29.3",
          "challenge": "GROUND OPERATIONS",
          "response": "AS REQ (FMC)"
        },
        {
          "id": "pmdg737.29.4",
          "challenge": "PASSENGER SIGNS",
          "response": "OFF"
        },
        {
          "id": "pmdg737.29.5",
          "challenge": "APU BLEED AIR",
          "response": "ON"
        },
        {
          "id": "pmdg737.29.6",
          "challenge": "ANIT COLL LIGHT",
          "response": "OFF"
        },
        {
          "id": "pmdg737.29.7",
          "challenge": "FUELPUMPS",
          "response": "OFF"
        },
        {
          "id": "pmdg737.29.8",
          "challenge": "L AFT FUEL PUMP",
          "response": "ON"
        },
        {
          "id": "pmdg737.29.9",
          "challenge": "ANTI-ICE",
          "response": "OFF"
        },
        {
          "id": "pmdg737.29.10",
          "challenge": "ELEC HYD PUMPS",
          "response": "OFF"
        },
        {
          "id": "pmdg737.29.11",
          "challenge": "ISOLATION VALVE",
          "response": "OPEN"
        },
        {
          "id": "pmdg737.29.12",
          "challenge": "FLIGHT DIRECTOR",
          "response": "OFF"
        },
        {
          "id": "pmdg737.29.13",
          "challenge": "ELECTRICAL POWER",
          "response": "ESTABLISH"
        },
        {
          "id": "pmdg737.29.14",
          "challenge": "EXTERIOR LIGHTS",
          "response": "AS REQ"
        }
      ]
    },
    {
      "id": "pmdg737.30",
      "name": "PARKING — SHUTDOWN CHECKLIST",
      "items": [
        {
          "id": "pmdg737.30.0",
          "challenge": "FUEL PUMPS",
          "response": "OFF"
        },
        {
          "id": "pmdg737.30.1",
          "challenge": "PROBE HEAT",
          "response": "OFF"
        },
        {
          "id": "pmdg737.30.2",
          "challenge": "HYDRAULIC PANEL",
          "response": "SET"
        },
        {
          "id": "pmdg737.30.3",
          "challenge": "FLAPS",
          "response": "UP"
        },
        {
          "id": "pmdg737.30.4",
          "challenge": "PARKING BRAKE",
          "response": "SET"
        },
        {
          "id": "pmdg737.30.5",
          "challenge": "ENG START SWITCHES",
          "response": "CUTOFF"
        },
        {
          "id": "pmdg737.30.6",
          "challenge": "WEATHER RADAR",
          "response": "OFF"
        }
      ]
    },
    {
      "id": "pmdg737.31",
      "name": "PARKING (continued)",
      "items": [
        {
          "id": "pmdg737.31.0",
          "challenge": "DEBOARDING",
          "response": "REQUEST",
          "note": "GSX"
        }
      ]
    },
    {
      "id": "pmdg737.32",
      "name": "SECURING",
      "items": [
        {
          "id": "pmdg737.32.0",
          "challenge": "IRS MODE SELECTORS",
          "response": "OFF"
        },
        {
          "id": "pmdg737.32.1",
          "challenge": "APU",
          "response": "OFF"
        },
        {
          "id": "pmdg737.32.2",
          "challenge": "L AFT FUEL PUMP",
          "response": "OFF"
        },
        {
          "id": "pmdg737.32.3",
          "challenge": "EMERGENCY EXIT LIGHTS",
          "response": "OFF"
        },
        {
          "id": "pmdg737.32.4",
          "challenge": "WINDOW HEAT",
          "response": "OFF"
        },
        {
          "id": "pmdg737.32.5",
          "challenge": "PACKS",
          "response": "OFF"
        },
        {
          "id": "pmdg737.32.6",
          "challenge": "CABIN LIGHTS",
          "response": "OFF"
        },
        {
          "id": "pmdg737.32.7",
          "challenge": "EXTERIOR LIGHTS",
          "response": "OFF"
        },
        {
          "id": "pmdg737.32.8",
          "challenge": "STANDBY POWER",
          "response": "OFF"
        },
        {
          "id": "pmdg737.32.9",
          "challenge": "BATTERY",
          "response": "OFF"
        }
      ]
    },
    {
      "id": "pmdg737.33",
      "name": "SECURING — SECURE CHECKLIST",
      "items": [
        {
          "id": "pmdg737.33.0",
          "challenge": "IRS's",
          "response": "OFF"
        },
        {
          "id": "pmdg737.33.1",
          "challenge": "EMERGENCY EXIT LIGHTS",
          "response": "OFF"
        },
        {
          "id": "pmdg737.33.2",
          "challenge": "WINDOW HEAT",
          "response": "OFF"
        },
        {
          "id": "pmdg737.33.3",
          "challenge": "PACKS",
          "response": "OFF"
        }
      ]
    }
  ]
};
